"""Build a randomly-initialised Atlas Flow model, for testing the machinery.

    python packaging/make_test_model.py --out build/test-model

CI cannot reach the cluster that holds the real 85 MB weights, and committing
them would put a binary blob in every clone. But the thing CI most needs to
prove -- that torch, PyInstaller, the server, the renderer and the websocket all
work on Windows -- does not depend on *which* weights are loaded, only on their
shapes being right.

So this constructs the same architecture from the same config with random
parameters, and an atlas whose geometry is plausible. Everything downstream
behaves identically; the audio is just noise rather than a pad. Any real
inference test still needs the real weights, and the checkpoint is stamped
accordingly so nobody mistakes one for the other.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import numpy as np
import torch

PRESETS = 50
TRAJECTORY_DIM = 128
ATLAS_DIM = 8
SCHEMA = "midibrave.atlas-flow.inference-weights.v1"


def build_atlas(rng: np.random.Generator, path: Path) -> None:
    """An atlas with the same shapes and roughly the same statistics."""
    components = rng.standard_normal((ATLAS_DIM, TRAJECTORY_DIM)).astype(np.float32)
    # Orthonormal, as a real PCA basis is; otherwise projection misbehaves.
    components, _ = np.linalg.qr(components.T)
    components = np.ascontiguousarray(components.T[:ATLAS_DIM], dtype=np.float32)

    coordinates = rng.uniform(-0.9, 0.9, (PRESETS, ATLAS_DIM)).astype(np.float32)
    scale = np.full(ATLAS_DIM, 2.0, dtype=np.float32)
    center = rng.standard_normal(TRAJECTORY_DIM).astype(np.float32) * 0.1
    anchors = (coordinates * scale) @ components + center

    # A symmetric mutual-kNN graph, k=4, with the diagonal cleared -- the
    # runtime uses it to decide which moves between presets are legal.
    distances = np.linalg.norm(coordinates[:, None, :] - coordinates[None, :, :], axis=-1)
    np.fill_diagonal(distances, np.inf)
    neighbours = np.argsort(distances, axis=1)[:, :4]
    knn = np.zeros((PRESETS, PRESETS), dtype=bool)
    for row, picks in enumerate(neighbours):
        knn[row, picks] = True
    knn &= knn.T

    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        path,
        preset_ids=np.array([f"test_s{index:06d}" for index in range(PRESETS)]),
        anchors=anchors.astype(np.float32),
        center=center,
        components=components,
        coordinates=coordinates,
        scale=scale,
        mutual_knn=knn,
    )


def build_weights(config: Path, atlas: Path, destination: Path) -> None:
    """Instantiate the real model from the real config, then never train it."""
    from midibrave.atlas_flow_config import load_atlas_flow_config
    from midibrave.atlas_flow_local import write_config
    from midibrave.atlas_flow_model import AtlasFlowSystem

    # Point the config at the atlas we just wrote, the same way the launcher does.
    scratch = destination.parent
    local = write_config(config, scratch / "test_config.yaml", {
        "atlas_path": atlas,
        "manifest": scratch / "unused-manifest.jsonl",
        "audio_root": scratch / "unused-audio",
        "feature_cache": scratch / "features",
        "trajectory_cache": scratch / "trajectories",
        "output_root": scratch / "runs",
    })

    # The same constructor the runtime uses, so the state dict it produces
    # loads with strict=True -- which is exactly the shape check worth having.
    parsed = load_atlas_flow_config(local)
    system = AtlasFlowSystem(parsed.model, parsed.data)
    state = {key: value.detach().clone() for key, value in system.state_dict().items()}
    torch.save({
        "system": state,
        "schema": SCHEMA,
        "stage": "test-random-init",
        "update": 0,
        "parameter_sha256": hashlib.sha256(
            b"".join(value.numpy().tobytes() for value in state.values())).hexdigest(),
        "source_checkpoint": "generated by packaging/make_test_model.py -- NOT TRAINED",
    }, destination)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("build/test-model"))
    parser.add_argument("--config", type=Path,
                        default=Path("configs/atlas_flow/kraken_pad_v1.yaml"))
    parser.add_argument("--seed", type=int, default=20260822)
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root / "src"))
    torch.manual_seed(args.seed)

    out = args.out if args.out.is_absolute() else root / args.out
    out.mkdir(parents=True, exist_ok=True)
    atlas = out / "pad-top50-atlas.npz"
    weights = out / "atlas-flow-pad-v1-weights.pt"

    build_atlas(np.random.default_rng(args.seed), atlas)
    config = args.config if args.config.is_absolute() else root / args.config
    build_weights(config, atlas, weights)

    print(f"atlas   {atlas}  ({atlas.stat().st_size / 1024:.0f} KiB)")
    print(f"weights {weights}  ({weights.stat().st_size / 1e6:.0f} MB, random init)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
